version: "3.8"

services:
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  postgres:
    image: "postgres:14-alpine"
    container_name: "postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "appdb"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  main:
    build:
      context: ./main
      dockerfile: Dockerfile
    container_name: "main"
    environment:
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
      DATABASE_URL: "postgres://postgres:password@postgres:5432/appdb"
    depends_on:
      - rabbitmq
      - postgres

  mailer:
    build:
      context: ./mailer
      dockerfile: Dockerfile
    container_name: "mailer"
    environment:
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
      DATABASE_URL: "postgres://postgres:password@postgres:5432/appdb"
    depends_on:
      - rabbitmq
      - postgres

volumes:
  postgres_data:
